name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: התקנת תלויות
        run: npm ci

      - name: יצירת מטריצה של קבצי בדיקה
        id: set-matrix
        run: |
          echo "matrix=$(ls tests | grep -v '^load$' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  run-tests:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_dir: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: התקנת תלויות
        run: npm ci

      - name: הרצת בדיקות עבור ${{ matrix.test_dir }}
        run: |
          npx playwright test tests/${{ matrix.test_dir }}/
